### ISSUE TITLE
Multiptocessing broken in Python 3.6

### ISSUE THREAD

**Issue by tamhanepd** [brandherd/PyParadise#6]
I downloaded PyParadise from github and installed it using `setup.py install`. When I run the example code, I get following errors:
```
prathamesh@Tamhane:~/soft/PyParadise-py3_only/examples$ source run_all.sh 
WARNING: VerifyWarning: It is strongly recommended that column names contain only upper and lower-case ASCII letters, digits, or underscores for maximum compatibility with other software (got '[Fe/H]'). [astropy.io.fits.column]
WARNING: VerifyWarning: It is strongly recommended that column names contain only upper and lower-case ASCII letters, digits, or underscores for maximum compatibility with other software (got '[A/Fe]'). [astropy.io.fits.column]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/prathamesh/.local/lib/python3.6/site-packages/PyParadise/spectrum1d.py", line 533, in fit_Kin_Lib_simple
    (coeff, bestfit_spec, chi2) = self.fitSuperposition(lib_vel)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/PyParadise/spectrum1d.py", line 351, in fitSuperposition
    libFit.fit(self._data, error, self._mask, negative=negative)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/PyParadise/fit_profile.py", line 102, in fit
    y[valid_pix]/error[valid_pix])
TypeError: Required argument 'n' (pos 3) not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prathamesh/.local/bin/ParadiseApp.py", line 697, in <module>
    app.run_SSP_fit(args.SSP_par, args.parallel, args.verbose)
  File "/home/prathamesh/.local/bin/ParadiseApp.py", line 211, in run_SSP_fit
    (vel_fit, vel_fit_err, Rvel, disp_fit, disp_fit_err, Rdisp, fitted, coeff, chi2, fiber, rss_model, mask, vel_trace, disp_trace) = normDataSub.fit_Kin_Lib_simple(lib_rebin, nlib_guess,vel_min, vel_max, disp_min, disp_max, min_y, max_y, excl_fit, iterations, mcmc_code, walkers, burn, samples, thin, verbose, store_chain, parallel)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/PyParadise/rss.py", line 243, in fit_Kin_Lib_simple
    result.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: Required argument 'n' (pos 3) not found
Stellar Continuum Fitting took 17 seconds
Traceback (most recent call last):
  File "/home/prathamesh/.local/bin/ParadiseApp.py", line 699, in <module>
    app.run_eline_fit(args.line_par, args.parallel, args.verbose)
  File "/home/prathamesh/.local/bin/ParadiseApp.py", line 323, in run_eline_fit
    line_fit = PyParadise.parameters.CustomMasks(parList['line_fit_region'].getValue())
  File "/home/prathamesh/.local/lib/python3.6/site-packages/PyParadise/parameters.py", line 98, in __init__
    infile = open(filename, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'lines.fit'
Emission Line Fitting took 5 seconds
Traceback (most recent call last):
  File "/home/prathamesh/.local/bin/ParadiseApp.py", line 701, in <module>
    app.run_bootstrap(args.SSP_par, args.line_par, args.bootstraps, args.modkeep, args.parallel, args.verbose)
  File "/home/prathamesh/.local/bin/ParadiseApp.py", line 473, in run_bootstrap
    hdu = pyfits.open(self.__outPrefix + '.stellar_table.fits')
  File "/home/prathamesh/.local/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 402, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1051, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/astropy/io/fits/file.py", line 175, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/prathamesh/.local/lib/python3.6/site-packages/astropy/io/fits/file.py", line 564, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/prathamesh/.local/lib/python3.6/site-packages/astropy/io/fits/util.py", line 397, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'NGC2691.COMB.RSS.stellar_table.fits'
Bootstrapping took 3 seconds
PyParadise output data cannot be found. Please check the prefix for the file names.
Plotting took 1 seconds
```

My Python version: 3.6.9
Scipy version: 1.5.4
emcee version: 3.0.2

**Comment by tamhanepd** [comment]
I had multiple versions of Scipy installed which was causing issues. Removing all scipy versions and reinstalling scipy worked.
